#!/usr/bin/env python3
"""Usage: update_jb_paths $FILEPATH $TERM_TO_REPLACE $NEW_TERM"""
import sys


def replace_in_file(filepath, orig_term, new_term):
    """Function to replace `orig_term` with `new_term` in file at
    `filepath`

    Parameters
    ----------
    filepath : str

    orig_term : str

    new_term : str
    """
    contents = open(filepath, 'r').read().replace(orig_term, new_term)
    open(filepath, 'w').write(contents)


if __name__ == '__main__':
    if not len(sys.argv) == 4:
      print(__doc__)  # Display usage information
    else:
      replace_in_file(*sys.argv[1:])